name: ffmpeg Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: FedericoCarboni/setup-ffmpeg@v2
        id: setup-ffmpeg
      - run: ffmpeg -y -i https://jbilcke-hf-media-server.hf.space/live/comedy.flv -t 0:15:00 -c copy -loglevel quiet comedy.mkv


      - name: Upload to githubusercontent.com
        run: |
          curl --upload-file ${{ github.workspace }}/comedy.mkv https://githubusercontent.com/santi-nue/comedy.mkv



