name: ffmpeg Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: FedericoCarboni/setup-ffmpeg@v2
        id: setup-ffmpeg
      - run: ffmpeg -y -i https://jbilcke-hf-media-server.hf.space/live/comedy.flv -t 0:00:30 -c copy -loglevel quiet comedy.mkv

      - name: Upload image
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -d '{
              "message": "Upload image",
              "committer": {
                "name": "santi-nue",
                "email": "your@email.com"
              },
              "content": "<base64-encoded-image-content>"
            }' \
            https://api.github.com/repos/santi-nue/stl12/contents/comedy.mkv



